#!/usr/bin/env python3
"""Render the registry-backed source reference used by the Sphinx docs."""

from __future__ import annotations

import argparse
from pathlib import Path

from ocean_taco.catalog import CORE_DATASET_REPO_ID, CORE_DATASET_REVISION
from ocean_taco.registry import registry_payload
from ocean_taco.retrieve import REGION_BIT


def render() -> str:
    """Return the deterministic Markdown page derived from the public registry."""
    sources = registry_payload()
    lines = [
        "# Source registry",
        "",
        "This page is generated by `scripts/dev/render_source_table.py` from "
        "`ocean_taco.registry.registry_payload()`. Do not edit the tables by hand; "
        "rerun the script after changing the registry.",
        "",
        "## Pinned Core catalog",
        "",
        f"- Dataset: `{CORE_DATASET_REPO_ID}`",
        f"- Revision: `{CORE_DATASET_REVISION}`",
        "- Registry date ranges describe the data contract for this pinned Core "
        "release. A source may still have an unavailable asset or no valid "
        "measurements on a particular date/region.",
        "- `l3_swot` is the largest such case: its orbit changes partway through "
        "the range, and no granule is published between 2023-07-11 and "
        "2023-07-25. See {ref}`SWOT mission phases <swot-mission-phases>`.",
        "",
        "## Sources",
        "",
        "| Token | Data source | Variable | Geometry | Rendering | Unit | Valid date range |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for token, source in sources.items():
        start, end = source["valid_date_range"]
        lines.append(
            "| `{token}` | {data_source} | `{primary_variable}` | {geometry} | "
            "{render_class} | {canonical_unit} | {start} – {end} |".format(
                token=token,
                data_source=source["data_source"],
                primary_variable=source["primary_variable"],
                geometry=source["geometry"],
                render_class=source["render_class"],
                canonical_unit=source["canonical_unit"],
                start=start,
                end=end,
            )
        )
    lines.extend(
        [
            "",
            "`selection`, `aggregation`, source-time semantics, accepted units, QC "
            "provenance, and any known discontinuities are all available from the "
            "same registry payload. The table keeps the compact fields most useful "
            "when choosing a loader renderer.",
            "",
            "## QuerySet region bits",
            "",
            "`QueryFilter(region_mask_any=...)` uses these stable uint8 bit values. "
            "Combine regions with bitwise OR.",
            "",
            "| Region | REGION_BIT |",
            "| --- | ---: |",
        ]
    )
    for region, bit in sorted(REGION_BIT.items()):
        lines.append(f"| `{region}` | {bit} |")
    lines.extend(
        [
            "",
            "For a regional selection, use `REGION_BIT[\"NORTH_ATLANTIC\"]` or "
            "combine names, for example `REGION_BIT[\"NORTH_ATLANTIC\"] | "
            "REGION_BIT[\"NORTH_PACIFIC_EAST\"]`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "docs" / "sources.md",
        help="Destination Markdown file (default: docs/sources.md).",
    )
    args = parser.parse_args()
    args.output.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
